### ISSUE TITLE
extract.py gives error for COCOImages

### ISSUE THREAD

**Issue by backpropper** [Cadene/vqa.pytorch#10]
extract.py calls self._raw() (https://github.com/Cadene/vqa.pytorch/blob/f24a006bc1ee5b2a51af169201db9e05219ba967/vqa/datasets/images.py#L63). But since self.split_name is not defined until the parent constructor is complete, it gives an Attribute error. 
Some suggestions - you can either pass the split_name to the _raw function or define it before calling the parent constructor in COCOImages.

**Comment by Cadene** [comment]
Thanks for your contribution. If you have enough time, you could send a PR. If not, I will update the code asap.

**Comment by backpropper** [comment]
Cool I will send in a PR.
