### ISSUE TITLE
MLBNoAtt does not use BayesianGRU

### ISSUE THREAD

**Issue by backpropper** [Cadene/vqa.pytorch#12]
In the default case (I guess MLBNoAtt), it uses normal GRU and not the Bayesian one. The README says otherwise.

**Comment by Cadene** [comment]
You are right, the default.yaml uses a GRU, not a Bayesian one: 
- https://github.com/Cadene/vqa.pytorch/blob/master/options/vqa2/default.yaml#L23
- https://github.com/Cadene/vqa.pytorch/blob/master/options/vqa/default.yaml#L22

Here, a BayesianGRU is used:
- https://github.com/Cadene/vqa.pytorch/blob/master/options/vqa/mutan_noatt_train.yaml#L22

I am sorry for this misleading information.

**Comment by Cadene** [comment]
I just added two options:
- https://github.com/Cadene/vqa.pytorch/blob/master/options/vqa/mlb_noatt_train.yaml
- https://github.com/Cadene/vqa.pytorch/blob/master/options/vqa2/mlb_noatt_train.yaml

**Comment by backpropper** [comment]
Thanks!
