### ISSUE TITLE
coco.py uses non-existent method os.execute

### ISSUE THREAD

**Issue by ssnl** [Cadene/vqa.pytorch#22]
The method doesn't exist in python 2.7, 3.5, or 3.6.

**Comment by Cadene** [comment]
It should be os.system.

Thanks for reporting this issue.

**Comment by ssnl** [comment]
Do you mind if I submit a PR to fix those?

**Comment by Cadene** [comment]
Please do so.

Thank you!

**Comment by Cadene** [comment]
Fixed: https://github.com/Cadene/vqa.pytorch/pull/23
