### ISSUE TITLE
Extracting features from Visual Genome gives error

### ISSUE THREAD

**Issue by mrfarazi** [Cadene/vqa.pytorch#29]
Hello, 

When extracting features from vgenome I get the following error.

`OSError: cannot identify image file 'data/vgenome/raw/images/2335991.jpg'`

It seems like this is a corrupt image and there are quite a few in the vgenome dataset. Are these invalid images handled manually or there is a built-in support.

Thanks in advance.

**Comment by Cadene** [comment]
We encountered a similar problem. We solved it by removing such images. https://github.com/Cadene/vqa.pytorch/blob/master/vqa/datasets/vgenome.py#L31

**Comment by mrfarazi** [comment]
Thanks. However, I needed to do a more manual approach to filter out the images in questions.
