### ISSUE TITLE
I do not have a demo server

### ISSUE THREAD

**Issue by youngjaean** [Cadene/vqa.pytorch#30]
Warning: 565/930911 words are not in dictionary, thus set UNK
Warning fusion.py: no visual embedding before fusion
Warning fusion.py: no question embedding before fusion
Warning fusion.py: no visual embedding before fusion
Warning fusion.py: no question embedding before fusion
Warning train.py: no optim checkpoint found at 'logs/vqa/mutan_noatt_train/best_optim.pth.tar'
This is an error. 

I didn't have enough hard disk capacity, so i deleted the raw data Does this matter?

**Comment by Cadene** [comment]
Warning: 565/930911 words are not in dictionary, thus set UNK
> just for information

Warning fusion.py: no visual embedding before fusion
Warning fusion.py: no question embedding before fusion
Warning fusion.py: no visual embedding before fusion
Warning fusion.py: no question embedding before fusion
> just for information (the same layer is used for the last fusion and the attention, both are a bit different and we add a warning, but you could simply remove it)

Warning train.py: no optim checkpoint found at 'logs/vqa/mutan_noatt_train/best_optim.pth.tar'
> It does matter only if you need to resume the training

Deleting the raw data is not a probem as long as you keep the raw directory (with no content).
https://github.com/Cadene/vqa.pytorch/blob/master/vqa/datasets/utils.py#L15

**Comment by youngjaean** [comment]
I do not understand. You do not need raw data? Do you just keep the directory? Does that solve the error on the demo server? Thank you for the reply.
