### ISSUE TITLE
Reproduce the problem using fusion scheme of concatenation

### ISSUE THREAD

**Issue by vuhoangminh** [Cadene/vqa.pytorch#33]
Hi Cadene,

Thank you so much for sharing the codes.

I am trying to reproduce vqa problem using two basic fusion scheme **element-wise sum** and **concatenation**.

What I tried is to set 
x_mm = torch.cat((x_q, x_v),0)  in fusion.py for concat case compared to 
x_mm = torch.mul(x_q, x_v) of MLBFusion

Am I right?

Thanks in advance.

**Comment by Cadene** [comment]
Yes :)

And you should certainly change the size of the nn.Linear as well.

**Comment by vuhoangminh** [comment]
Thank you so much for your confirmation Cadene.
