### ISSUE TITLE
'OpenEnded_mscoco_val2014_model_accuracy.json' is not created

### ISSUE THREAD

**Issue by zizhu1234** [Cadene/vqa.pytorch#38]
Hi :
     The 'OpenEnded_mscoco_val2014_model_accuracy.json'  is needed in line 26 in 'visu.py', but I can not find the function to generate it in your 'train.py'.  When the 'trainsplit = train' , it can not generete the 'OpenEnded_mscoco_val2014_model_accuracy.json' . And only 'OpenEnded_mscoco_val2014_model_result.json' was cteated. I want to know what is wrong with it?

Thanks

**Comment by zwx8981** [comment]
Hi, @zizhu1234, I have the same question, how did you get the accuracy?

**Comment by Cadene** [comment]
@zwx8981 It should be created right here: 
https://github.com/Cadene/vqa.pytorch/blob/master/train.py#L287

It is really messy :/
