### ISSUE TITLE
The Link doesn't work: MutanNoAtt trained on the VQA 1.0 trainset

### ISSUE THREAD

**Issue by haniomar** [Cadene/vqa.pytorch#42]
These Links aren't working using (wget) nor direct from the browser 
wget http://webia.lip6.fr/~cadene/Downloads/vqa.pytorch/logs/vqa/mutan_noatt_train.zip 
wget http://webia.lip6.fr/~cadene/Downloads/vqa.pytorch/logs/vqa/mlb_att_trainval.zip 
wget http://webia.lip6.fr/~cadene/Downloads/vqa.pytorch/logs/vqa/mutan_att_trainval.zip 

How can I get them?
Thank you!

**Comment by Cadene** [comment]
@haniomar The pretrained models urls have been restored !
