### ISSUE TITLE
How did you create the attention maps in your readme?

### ISSUE THREAD

**Issue by Karol-G** [Cadene/vqa.pytorch#51]
Hey,

in your readme you showed two attention maps. How did you create these?

![grafik](https://user-images.githubusercontent.com/3471895/74587516-ce98f780-4ff3-11ea-8d99-5fe9206869a6.png)

Best,
Karol

**Comment by Cadene** [comment]
I used this library https://github.com/durandtibo/heatmap

**Comment by Karol-G** [comment]
No sorry I meant how did you get the model attentions in the first place?
Not how to combine them ;)

**Comment by Cadene** [comment]
I used this: https://github.com/Cadene/vqa.pytorch/blob/69d7a43fb02c0332176915a4a23fc47cab08b1d2/vqa/models/att.py#L99

:)

**Comment by Karol-G** [comment]
Thanks :)

One more question: Is the model attention class specific?
So for example if the question for the image above would be "What do you see?" and the best model prediction would be "person" with a probability of 51% and the second best "laptop" with 49%. Would the model attention be focused only on the people (class specific) or on the people and the laptop (not class specific)?

**Comment by Cadene** [comment]
It really depends. Attention maps are sometimes difficult to interpret qualitatively. The example illustrating the article was cherry picked

**Comment by Karol-G** [comment]
> 
> 
> I used this:
> 
> https://github.com/Cadene/vqa.pytorch/blob/69d7a43fb02c0332176915a4a23fc47cab08b1d2/vqa/models/att.py#L99
> 
> :)

how did you create the heatmap from `self.list_att`? What kind of transformations did you apply?

**Comment by Cadene** [comment]
I created one heatmap per element in the list

**Comment by tihartmann** [comment]
Hi Cadene, Thanks for sharing the code and models!
I was trying to reproduce the heat-maps based on your comments above. However, I was not able to do so. Would you be able to share how exactly you computed them? I tried the following and tried different values for sigma:

"""
def get_heatmap(img, model, sigma=18):
    att = model.model.list_att
    heat_maps = [ndimage.filters.gaussian_filter(att.cpu(), sigma=sigma) for att in att]
    heat_map = sum(heat_maps) / 4
    heatmap.add(np.array(img), heat_map, alpha=.6, cmap="turbo")
"""
The following is an example output given the question "What color is the cat?" and using MLBatt. Thanks a lot in advance, I would greatly appreciate it if you could help with this!
![image](https://user-images.githubusercontent.com/34128682/122595695-1f49b600-d069-11eb-9dda-028d54f0242e.png)
