### ISSUE TITLE
Performance of MLB

### ISSUE THREAD

**Issue by gaopeng-eugene** [Cadene/vqa.pytorch#7]
Why your MLB baseline is so low?

**Comment by Cadene** [comment]
You are talking about the experimental results of table1, I guess.
https://arxiv.org/pdf/1705.06676.pdf

> To point out the performance variation due to the fusion
> modules, we first compare MUTAN to state-of-the-art bilinear
> models, under the same experimental framework. We
> do not use attention models here. 

So in those experiments image features are of size 2048 instead of 14x14x2048.

**Comment by gaopeng-eugene** [comment]
What is the performance of MLB+attn in your code?

**Comment by Cadene** [comment]
You can download the zip file.
